resources:
  repositories:
    - repository: owaspzapui
      type: github
      endpoint: soufianem370
      name: soufianem370/owasp-zap-scan
      ref: refs/heads/master

jobs:
- template: owasp-zap-ui-scan-template.yml@owaspzapui
  parameters:
    url: https://www.hespress.com/
    publishAsTestResults: variables.PublishTestResults
